<?php
    session_start();
    include("Model/db_data_functions.php");
    include("Model/pesquisar.php");
    include("View/header.php");
    include("View/top_menu.php");
    include("View/pesquisar.php");
    include("View/resultados_pesquisa.php");
?>